rvm: 
  - 1.8.7
  - 1.9.3
env:
  - PUPPET_VERSION=2.7.11
  - PUPPET_VERSION=3.3.1
language: ruby
before_script: "gem install --no-ri --no-rdoc bundler"
script: 'bundle exec rake validate && bundle exec rake lint && SPEC_OPTS="--format documentation" bundle exec rake spec'
gemfile: Gemfile
